college_phone/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("contacts.urls"))
]

contacts/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import CollegeView

app_name ="contacts"

urlpatterns = [
    path("",CollegeView.as_view(),name="search")
]

contacts/models.py
from django.db import models

# Create your models here.



class CollegeName(models.Model):

    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)

class CollegeContact(models.Model):

    emails = models.TextField()
    numbers = models.TextField()
    college=models.ForeignKey(CollegeName,on_delete=models.CASCADE)

    def __str__(self):
        return self.college

contacts/forms.py
from django.forms import ModelForm
from .models import CollegeName



class CollegeForm(ModelForm):

    class Meta:
        model = CollegeName
        fields=["name"]

contacts/views.py
from django.shortcuts import render
from django.views import View
from .forms import CollegeForm
from .models import CollegeName,CollegeContact
from .helpers import get_results,get_phone_emails



# Create your views here.


class CollegeView(View):


    def get(self,request):
        form =CollegeForm()
        ctx={"form":form}
        return render(request,"contacts/home.html",ctx)


    def post(self,request):

        if CollegeName.objects.filter(name=request.POST['name']).exists():
            id = CollegeName.objects.filter(name=request.POST['name'])[0].id
            print(id)
            print(id)

            obj=CollegeContact.objects.filter(college=str(id))[0]

            def str_to_list(str1):
                str1=str1.strip('{}').split(', ')
                for i in range(len(str1)):
                    str1[i]=str1[i].strip("''")
                return str1

            obj={"numbers":str_to_list(obj.numbers),"emails":str_to_list(obj.emails)}

        else:
            form = CollegeForm(request.POST)




            results = get_results(request.POST['name'])
            emails,phones = get_phone_emails(results)



            if emails or phones:
                form.save()
                id = CollegeName.objects.filter(name=request.POST['name'])
                obj = CollegeContact(emails=emails, numbers=phones, college=id[0])

                obj.save()
            else:
                obj=[]



        ctx={"object":obj,"name":request.POST['name']}
        return render(request,"contacts/list.html",ctx)

contacts/templates/contacts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>College Search</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>

<div class="container">

<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="search">
</form>

</div>

</body>
</html>

contacts/templates/contacts/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Information</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>

<div class="container">
    <div class="row">
        <h2>Results For {{name}}:</h2>

        <div class="col s6">

 <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Emails</span>

<br><br>


{% if object.emails %}
{% for i in object.emails %}
{{i}}<br>
{% endfor %}
{% else %}
<h4>No emails Found</h4>
{% endif %}
<br><br><br>
 </div>
        </div>
 </div>


    <div class="col s6">
         <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Phone Numbers</span>

{% if object.numbers %}

{% for x in object.numbers %}
{{x}}<br>
{% endfor %}
{% else %}
<h4>No Numbers Found</h4>
{% endif %}
    </div>
    </div>
    </div>
    </div>
    <a href="{% url 'contacts:search' %}">Go Back</a>
</div>
</body>
</html>